# Site
# repository: VioletaCalvo/jekyll-forked-resume
favicon: images/favicon.ico

# Personal info
name: Violeta CALVO
title: Full Stack Engineer
email: violeta.itt@gmail.com
# website: www.github.com/VioletaCalvo/jekyll-forked-resume

# Social links
# twitter_username: facespics
github_username:  VioletaCalvo
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: katuarraina
linkedin_username: violeta-calvo-ilundain-46b47932
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/VioletaCOLOR.jpg
about_content: | # this will include new lines to allow paragraphs
  I’m an engineer with a 4 year experience creating and building full-stack applications, participating in all the phases of software development. I was the only developer for 3 years in my last job. I’m mainly a Meteor full-stack developer, but, I have always thought, that what I can learn is more important than what I already know. I’m looking for new opportunities ideally working remotely in a startup.
I am most skilled in: <mark>Meteor</mark> and <mark>learning</mark>

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Languages
   - Spanish - native language
   - English - B2 (professional)
   - French - B2 (professional)
   - Basque - B1

  When I'm not creating software these are my favourites activities:
   - Playing with my 2 year-old son
   - Singing and playing guitar
   - Making photos
   - Knitting
   - Learning some intereresting thing

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
